export const ACTION_TYPES = {
    FETCH_LOGIN_LENG: "FETCH_LOGIN_LENG",
    FETCH_WAITING_LIST_LENG : "FETCH_WAITING_LIST_LENG",
    FETCH_LOGIN : "FETCH_LOGIN",
    FETCH_WAITING_DATA : "FETCH_WAITING_DATA",
    FETCH_INTERPRETATION_DATA : "FETCH_INTERPRETATION_DATA",
    DATA_LOADING: "DATA_LOADING",
    SEND_INTERPRETATION_DATA : "SEND_INTERPRETATION_DATA",
    HEADER_COLOR : "HEADER_COLOR",
    SEND_IMG_QUALITY_DATA : "SEND_IMG_QUALITY_DATA"
};