export const baseUrl = "http://s.eyedx.org"

export const loginUrl = baseUrl + "/login"
export const loginLangUrl = loginUrl + "/lang"
export const waitingListUrl = baseUrl + "/waiting/list"
export const waitingListLangUrl = waitingListUrl + "/lang"
export const interpreationUrl = baseUrl + "/interpretation/"
export const info = "/info"
export const send = "/send"
export const vote = "/vote"
